language: node_js
node_js:
  - "8"
deploy:
  provider: s3
  access_key_id: AKIAJ64EYVBL22CNNP5A
  secret_access_key:
    secure: D2g06S8uG60NhE2HwwnWq68qOsksZ2CxTtpEIYbzgak9HfOFLx9ztbTFrt6ghRG5aatK+9/Qw7rTpG4Dv8P0yFfMyd1tjmyazgLqGrThZW3BEGxghb5xoesw3W62+1pOjZuyaM0NTPmYuEfZslEIj2zZ/HiaGBfybLehjZNTafszTlnSc0I1rssVJ8RrZRPzuV+PbfNA5WVWF++R95ONiPZ9PDj+ikOIyI+eSP9zsScqHGRd9aMVkVCtIAVtTfXqbDUg2LFQL4cIFHVXPfyGWW277OXR6zcRct9ia2k/2RbVCtg1EiYg4ohXyHvmBjwq5quvanpENbluRuXCwIzdqnr1q37N2giGZ7UUvdLDkWvW5ZwxBhv3iv11OTqfRzynUpSX4shA+9tdlOnQYpM8sa5tcTYDOOfd0wV21B9sl5LEj0hBAKv7FqkuRSy8vKEwAKkNY2ezjfeLwZK/p1uTa7d6ugDjRwWeLmvRT1wKmc4una1BCGm+lep40phJvUQFlIsmiJuWN2aa4dRcfcKf/ZKnzgx+n8m4LKNCTUmBw5YYVyDR2XIqDzgZdQXIhovFBxXkq3+JlxrJLUAJl/05EdczhivmvJHfEvntgeiHmZT9yec52/4uhqJamwdVW4tRXcZYCv6ugIPp2AevkRZ13r29I4/RFI64+PAfGXGwcAE=
  bucket: internetdjur.se
  local-dir: public
  acl: public_read
  endpoint: internetdjur.se.s3-website-eu-west-1.amazonaws.com
  on:
    branch: master
    repo: cskeppstedt/internetdjur.se
